### PR TITLE
Simplify root build.gradle

### PR DESCRIPTION
**Pull request by Polaris257**

### CODE REVIEW

**Comment by shedaniel** [comment]
This is undesired, we don't want to have loom on the root project.

**Comment by Polaris257** [comment]
What? Does `subprojects` also apply to the root project? I deleted `allprojects`

**Comment by shedaniel** [comment]
Ah you did that, that's fine then, does this also set the artifact base, group and version of the project?

**Comment by Polaris257** [comment]
I haven't tested that yet, but do those need to be set in the root project?

**Comment by belak** [comment]
As far as I can tell, this is actually better than the current setup because it doesn't create empty artifacts in the root project. It does this by removing the java plugin from the root and only applying it to subprojects.

**Comment by MaxNeedsSnacks** [comment]
This repo is being archived in favour of Architectury Templates, so this will unfortunately not be merged

**Pull request closed without merging**
